#!/usr/bin/env python3
import secrets
import sys

def generate_password(word_count: int) -> None:
    with open("/usr/share/dict/words") as f:
        words = [word.strip() for word in f if "'" not in word and " " not in word and not word[0].isupper()]
        password = " ".join(secrets.choice(words) for i in range(word_count))
        # print(f"words:    {password}")
        # print(f"password: {password.replace(' ', '')}")
        print(password.replace(' ', ''))



def get_input():
    if len(sys.argv) == 2 and sys.argv[1].strip():
        word_count = int(sys.argv[1])
        password_count = 1
    elif len(sys.argv) == 3 and sys.argv[1].strip() and sys.argv[2].strip():
        word_count = int(sys.argv[1])
        password_count = int(sys.argv[2]) 
    else:
        word_count = 4
        password_count = 1

    return word_count, password_count


def main():
    word_count, password_count = get_input()
    for i in range(password_count):
        generate_password(word_count=word_count)


if __name__ == "__main__":
    main()

